name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_firmware:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Orbita3d beta
      run: cargo build --release --features orbita3d_beta
    - name: Build Orbita2d beta
      run: cargo build --release --features orbita2d_beta
    - name: Build Orbita3d gamma
      run: cargo build --release --features orbita3d_gamma
    - name: Build Orbita2d gamma
      run: cargo build --release --features orbita2d_gamma
    - name: Build Orbita3d pvt
      run: cargo build --release --features orbita3d_pvt
    - name: Build Orbita2d pvt
      run: cargo build --release --features orbita2d_pvt
    # - name: Run tests
    #   run: cargo test --verbose 

  build_examples:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v3
      - name: Build Hall example for Orbita3d beta
        run: cargo build --release --features orbita3d_beta --bin test_Hall
      - name: Build Hall example for Orbita3d pvt
        run: cargo build --release --features orbita3d_pvt --bin test_Hall
      - name: Build MotorControl example for Orbita3d beta
        run: cargo build --release --features orbita3d_beta --bin test_MotorControl
      - name: Build MotorControl example for Orbita3d pvt
        run: cargo build --release --features orbita3d_pvt --bin test_MotorControl
      - name: Build Ring example for Orbita2d beta
        run: cargo build --release --features orbita2d_beta --bin test_Ring
      - name: Build Ring example for Orbita2d pvt
        run: cargo build --release --features orbita2d_pvt --bin test_Ring
      - name: Build Center example for Orbita2d beta
        run: cargo build --release --features orbita2d_beta --bin test_Center
      - name: Build Center example for Orbita2d pvt
        run: cargo build --release --features orbita2d_pvt --bin test_Center
      - name: Build Temperature example for Orbita2d beta
        run: cargo build --release --features orbita2d_beta --bin test_Temperature
      - name: Build Temperature example for Orbita2d pvt
        run: cargo build --release --features orbita2d_pvt --bin test_Temperature

  build_bench:
  
      runs-on: ubuntu-latest
  
      steps:
      - name: Build write zeros bench for Orbita2d pvt
        run: cargo build --release --features orbita2d_pvt --bin bench_Orbita2dWriteZeros
      - name: Build write zeros bench for Orbita3d pvt
        run: cargo build --release --features orbita3d_pvt --bin bench_Orbita3dWriteZeros
      - name: Build write zeros bench for Orbita2d pvt
        run: cargo build --release --features orbita2d_gamma --bin bench_Orbita2dWriteZeros
      - name: Build write zeros bench for Orbita3d pvt
        run: cargo build --release --features orbita3d_gamma --bin bench_Orbita3dWriteZeros
