name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Orbirta3D
      run: cargo build --verbose --features ecx22 --features orbita3d
    - name: Build Orbita2D
      run: cargo build --verbose --features ec45 --features orbita2d
    # - name: Run tests
    #   run: cargo test --verbose
